services:
  - type: web
    name: jaskron-technologies-api
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
